import type { Metadata } from 'next'
import { MapPin, Clock, Car, Shield, ArrowRight, Users, Phone, Mail, Calendar, Tag, CheckCircle, Award, Calculator, Gift, Plane, Navigation, Timer, Mountain, Route } from 'lucide-react'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Alquiler Aeropuerto Tetuán 2025 - Servicio Exprés ✓ Desde 175 DH',
  description: 'Alquiler coche en el aeropuerto de Tetuán ✓ Servicio exprés ✓ Recepción en terminal ✓ Desde 175 DH/día ✓ Seguimiento de vuelos ✓ Asistencia 24/7 ✓ Reserva fácil.',
  keywords: 'alquiler coche aeropuerto tetuan, car rental tetouan airport, alquiler auto aeropuerto tetuan',
  alternates: {
    canonical: 'https://www.nassohcar.com/es/blog/alquiler-aeropuerto-tetuan'
  },
  openGraph: {
    title: 'Alquiler Aeropuerto Tetuán 2025 - Servicio Exprés ✓ Desde 175 DH',
    description: 'Alquiler coche en el aeropuerto de Tetuán ✓ Servicio exprés ✓ Recepción terminal ✓ Desde 175 DH/día ✓ Seguimiento de vuelos.',
    images: ['/tetouan-airport-car-rental.webp'],
  },
}

export default function BlogAlquilerAeropuertoTetuanES() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-blue-50">
      <div className="relative bg-gradient-to-r from-sky-900 via-blue-800 to-indigo-900 text-white overflow-hidden">
        <div className="absolute inset-0 bg-black/20"></div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
          <div className="text-center">
            <div className="flex items-center justify-center mb-6"><Plane className="h-6 w-6 text-sky-400 mr-2" /><span className="text-sky-400 font-semibold text-lg">Aeropuerto Sania Ramel</span></div>
            <h1 className="text-4xl md:text-6xl font-bold mb-6 bg-gradient-to-r from-sky-400 via-blue-300 to-indigo-400 bg-clip-text text-transparent leading-tight">Alquiler Aeropuerto Tetuán</h1>
            <p className="text-xl md:text-2xl text-gray-300 max-w-4xl mx-auto leading-relaxed mb-8">Servicio exprés en el aeropuerto de Tetuán. Recepción en terminal, seguimiento de vuelos y vehículo listo a tu llegada.</p>
            <div className="flex flex-wrap justify-center gap-4 text-sm mb-8"><div className="flex items-center bg-white/10 rounded-full px-4 py-2"><Calendar className="h-4 w-4 mr-2" /><span>Actualizado el 15 Enero 2025</span></div><div className="flex items-center bg-white/10 rounded-full px-4 py-2"><Clock className="h-4 w-4 mr-2" /><span>6 min de lectura</span></div><div className="flex items-center bg-white/10 rounded-full px-4 py-2"><Tag className="h-4 w-4 mr-2" /><span>Aeropuerto</span></div></div>
            <Link href="/es/fleet" className="inline-flex items-center bg-gradient-to-r from-sky-500 to-blue-500 hover:from-sky-600 hover:to-blue-600 text-white font-bold py-4 px-8 rounded-full transition-all duration-300 transform hover:scale-105 shadow-lg">Reservar Aeropuerto<ArrowRight className="ml-2 h-5 w-5" /></Link>
          </div>
        </div>
      </div>

      <div className="py-16 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12"><h2 className="text-3xl font-bold text-gray-900 mb-4">Servicio exprés aeropuerto Tetuán</h2><p className="text-xl text-gray-600">Tu coche te espera al aterrizar</p></div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
            <div className="bg-gradient-to-br from-sky-50 to-blue-50 p-6 rounded-2xl"><div className="text-4xl font-bold text-sky-600 mb-2">5 min</div><div className="text-gray-600 font-medium">Recogida exprés</div></div>
            <div className="bg-gradient-to-br from-blue-50 to-indigo-50 p-6 rounded-2xl"><div className="text-4xl font-bold text-blue-600 mb-2">24/7</div><div className="text-gray-600 font-medium">Servicio vuelos</div></div>
            <div className="bg-gradient-to-br from-indigo-50 to-purple-50 p-6 rounded-2xl"><div className="text-4xl font-bold text-indigo-600 mb-2">100%</div><div className="text-gray-600 font-medium">Seguimiento automático</div></div>
            <div className="bg-gradient-to-br from-purple-50 to-pink-50 p-6 rounded-2xl"><div className="text-4xl font-bold text-purple-600 mb-2">175 DH</div><div className="text-gray-600 font-medium">Precio desde/día</div></div>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="grid lg:grid-cols-3 gap-12">
          <div className="lg:col-span-2">
            <article className="prose prose-lg max-w-none">
              <h2 className="text-3xl font-bold text-gray-900 mb-6 flex items-center"><Plane className="h-8 w-8 text-sky-600 mr-3" />Aeropuerto Tetuán Sania Ramel</h2>
              <p className="text-gray-700 leading-relaxed mb-6">Con nuestro servicio de <strong>alquiler aeropuerto Tetuán</strong>, disfrutas de recepción en terminal y recogida exprés para empezar tu viaje inmediatamente.</p>
              <div className="bg-gradient-to-r from-sky-50 to-blue-50 p-6 rounded-2xl mb-8"><h3 className="text-2xl font-bold text-gray-900 mb-4 flex items-center"><Award className="h-6 w-6 text-sky-600 mr-2" />Ventajas del servicio aeropuerto</h3><ul className="space-y-3"><li className="flex items-start"><CheckCircle className="h-5 w-5 text-sky-500 mr-3 mt-1 flex-shrink-0" /><span><strong>Recepción en terminal</strong>: agente con cartel nominativo</span></li><li className="flex items-start"><CheckCircle className="h-5 w-5 text-sky-500 mr-3 mt-1 flex-shrink-0" /><span><strong>Seguimiento de vuelos</strong>: adaptación automática a retrasos</span></li><li className="flex items-start"><CheckCircle className="h-5 w-5 text-sky-500 mr-3 mt-1 flex-shrink-0" /><span><strong>Recogida 5 min</strong>: formalidades rápidas</span></li><li className="flex items-start"><CheckCircle className="h-5 w-5 text-sky-500 mr-3 mt-1 flex-shrink-0" /><span><strong>Servicio 24/7</strong>: todos los vuelos</span></li></ul></div>

              <h3 className="text-2xl font-bold text-gray-900 mb-6 flex items-center"><Navigation className="h-6 w-6 text-sky-600 mr-2" />Proceso de recogida aeropuerto</h3>
              <p className="text-gray-700 leading-relaxed mb-6">Proceso optimizado para tu <strong>alquiler aeropuerto Tetuán</strong>:</p>
              <div className="grid md:grid-cols-1 gap-6 mb-8">
                <div className="bg-white border-2 border-sky-200 rounded-2xl p-6 shadow-sm hover:shadow-md transition-shadow"><div className="flex items-start"><div className="bg-sky-500 text-white rounded-full w-10 h-10 flex items-center justify-center font-bold mr-4 mt-1">1</div><div className="flex-1"><h4 className="font-bold text-xl text-gray-900 mb-3">Reserva y confirmación</h4><div className="grid md:grid-cols-2 gap-4"><ul className="text-gray-600 space-y-2"><li>• <strong>Reserva</strong>: online o teléfono</li><li>• <strong>Datos de vuelo</strong>: número y hora</li><li>• <strong>Confirmación</strong>: SMS y email</li></ul><ul className="text-gray-600 space-y-2"><li>• <strong>Contacto agente</strong>: 24h antes</li><li>• <strong>Instrucciones</strong>: punto de encuentro</li><li>• <strong>Urgencias</strong>: número 24/7</li></ul></div></div></div></div>
                <div className="bg-white border-2 border-blue-200 rounded-2xl p-6 shadow-sm hover:shadow-md transition-shadow"><div className="flex items-start"><div className="bg-blue-500 text-white rounded-full w-10 h-10 flex items-center justify-center font-bold mr-4 mt-1">2</div><div className="flex-1"><h4 className="font-bold text-xl text-gray-900 mb-3">Llegada y recepción</h4><div className="grid md:grid-cols-2 gap-4"><ul className="text-gray-600 space-y-2"><li>• <strong>Seguimiento</strong>: tiempo real</li><li>• <strong>Recepción terminal</strong>: salida equipajes</li><li>• <strong>Cartel nominativo</strong>: tu nombre visible</li></ul><ul className="text-gray-600 space-y-2"><li>• <strong>Agente dedicado</strong>: multilingüe</li><li>• <strong>Asistencia equipaje</strong>: si necesario</li><li>• <strong>Transfer vehículo</strong>: parking seguro</li></ul></div></div></div></div>
                <div className="bg-white border-2 border-indigo-200 rounded-2xl p-6 shadow-sm hover:shadow-md transition-shadow"><div className="flex items-start"><div className="bg-indigo-500 text-white rounded-full w-10 h-10 flex items-center justify-center font-bold mr-4 mt-1">3</div><div className="flex-1"><h4 className="font-bold text-xl text-gray-900 mb-3">Formalidades exprés</h4><div className="grid md:grid-cols-2 gap-4"><ul className="text-gray-600 space-y-2"><li>• <strong>Documentos</strong>: permiso + pasaporte/CIN</li><li>• <strong>Contrato</strong>: pre-rellenado</li><li>• <strong>Pago</strong>: tarjeta, efectivo</li></ul><ul className="text-gray-600 space-y-2"><li>• <strong>Estado vehículo</strong>: inspección conjunta</li><li>• <strong>Entrega llaves</strong>: + documentos</li><li>• <strong>Duración total</strong>: 5 minutos</li></ul></div></div></div></div>
                <div className="bg-white border-2 border-purple-200 rounded-2xl p-6 shadow-sm hover:shadow-md transition-shadow"><div className="flex items-start"><div className="bg-purple-500 text-white rounded-full w-10 h-10 flex items-center justify-center font-bold mr-4 mt-1">4</div><div className="flex-1"><h4 className="font-bold text-xl text-gray-900 mb-3">Salida y asistencia</h4><div className="grid md:grid-cols-2 gap-4"><ul className="text-gray-600 space-y-2"><li>• <strong>Briefing</strong>: rutas y destinos</li><li>• <strong>GPS configurado</strong>: destinos populares</li><li>• <strong>Guía región</strong>: Tetuán y alrededores</li></ul><ul className="text-gray-600 space-y-2"><li>• <strong>Contacto 24h</strong>: asistencia permanente</li><li>• <strong>Devolución flexible</strong>: aeropuerto o ciudad</li><li>• <strong>Seguimiento</strong>: soporte continuo</li></ul></div></div></div></div>
              </div>

              <h3 className="text-2xl font-bold text-gray-900 mb-6 flex items-center"><Car className="h-6 w-6 text-sky-600 mr-2" />Flota disponible en aeropuerto</h3>
              <p className="text-gray-700 leading-relaxed mb-6">Nuestra flota en el <strong>aeropuerto de Tetuán</strong> se adapta a todas las necesidades:</p>
              <div className="grid md:grid-cols-2 gap-6 mb-8">
                <div className="bg-white border-2 border-sky-200 rounded-2xl p-6 shadow-sm hover:shadow-md transition-shadow"><h4 className="font-bold text-xl text-gray-900 mb-4 flex items-center"><Car className="h-5 w-5 text-sky-600 mr-2" />Económico (175-190 DH)</h4><ul className="text-gray-600 space-y-2 mb-4"><li>• <strong>Modelos</strong>: Clio, Logan, Sandero</li><li>• <strong>Ideal</strong>: pareja, ciudad</li><li>• <strong>Equipaje</strong>: 2 maletas cabina</li><li>• <strong>Consumo</strong>: 5-6L/100km</li></ul><div className="bg-sky-100 text-sky-800 text-sm font-semibold px-3 py-1 rounded-full inline-block">Disponible inmediatamente</div></div>
                <div className="bg-white border-2 border-blue-200 rounded-2xl p-6 shadow-sm hover:shadow-md transition-shadow"><h4 className="font-bold text-xl text-gray-900 mb-4 flex items-center"><Users className="h-5 w-5 text-blue-600 mr-2" />Familiar (220-250 DH)</h4><ul className="text-gray-600 space-y-2 mb-4"><li>• <strong>Modelos</strong>: Scenic, Lodgy, C4 Picasso</li><li>• <strong>Ideal</strong>: familia, grupo</li><li>• <strong>Equipaje</strong>: 4-5 maletas</li><li>• <strong>Confort</strong>: climatización, GPS</li></ul><div className="bg-blue-100 text-blue-800 text-sm font-semibold px-3 py-1 rounded-full inline-block">Confort familia</div></div>
                <div className="bg-white border-2 border-indigo-200 rounded-2xl p-6 shadow-sm hover:shadow-md transition-shadow"><h4 className="font-bold text-xl text-gray-900 mb-4 flex items-center"><Mountain className="h-5 w-5 text-indigo-600 mr-2" />SUV (280-320 DH)</h4><ul className="text-gray-600 space-y-2 mb-4"><li>• <strong>Modelos</strong>: Duster, Captur, Panda 4x4</li><li>• <strong>Ideal</strong>: montaña, aventura</li><li>• <strong>Ventajas</strong>: 4x4, altura</li><li>• <strong>Destinos</strong>: Rif, Chefchaouen</li></ul><div className="bg-indigo-100 text-indigo-800 text-sm font-semibold px-3 py-1 rounded-full inline-block">Aventura montaña</div></div>
                <div className="bg-white border-2 border-purple-200 rounded-2xl p-6 shadow-sm hover:shadow-md transition-shadow"><h4 className="font-bold text-xl text-gray-900 mb-4 flex items-center"><Shield className="h-5 w-5 text-purple-600 mr-2" />Premium (350-400 DH)</h4><ul className="text-gray-600 space-y-2 mb-4"><li>• <strong>Modelos</strong>: Passat, Accord, cabriolets</li><li>• <strong>Ideal</strong>: negocios, prestigio</li><li>• <strong>Equipamiento</strong>: cuero, GPS premium</li><li>• <strong>Servicio</strong>: prioridad, concierge</li></ul><div className="bg-purple-100 text-purple-800 text-sm font-semibold px-3 py-1 rounded-full inline-block">Luxe y prestigio</div></div>
              </div>

              <h3 className="text-2xl font-bold text-gray-900 mb-6 flex items-center"><Route className="h-6 w-6 text-sky-600 mr-2" />Destinos desde el aeropuerto</h3>
              <p className="text-gray-700 leading-relaxed mb-6">Explora el norte marroquí nada más salir del <strong>aeropuerto de Tetuán</strong>:</p>
              <div className="overflow-x-auto mb-8">
                <table className="w-full bg-white border border-gray-200 rounded-xl shadow-sm">
                  <thead className="bg-gradient-to-r from-sky-50 to-blue-50">
                    <tr>
                      <th className="px-6 py-4 text-left font-semibold text-gray-900">Destino</th>
                      <th className="px-6 py-4 text-center font-semibold text-sky-600">Distancia</th>
                      <th className="px-6 py-4 text-center font-semibold text-blue-600">Tiempo</th>
                      <th className="px-6 py-4 text-center font-semibold text-indigo-600">Ruta</th>
                      <th className="px-6 py-4 text-center font-semibold text-purple-600">Interés</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-200">
                    <tr className="hover:bg-gray-50"><td className="px-6 py-4 font-medium text-gray-900">Centro Tetuán</td><td className="px-6 py-4 text-center text-sky-600 font-semibold">5 km</td><td className="px-6 py-4 text-center text-blue-600 font-semibold">10 min</td><td className="px-6 py-4 text-center text-indigo-600 font-semibold">Directa</td><td className="px-6 py-4 text-center text-purple-600 font-semibold">★★★★★</td></tr>
                    <tr className="bg-sky-50 hover:bg-sky-100"><td className="px-6 py-4 font-medium text-gray-900">Martil (playa)</td><td className="px-6 py-4 text-center text-sky-600 font-semibold">15 km</td><td className="px-6 py-4 text-center text-blue-600 font-semibold">20 min</td><td className="px-6 py-4 text-center text-indigo-600 font-semibold">Costera</td><td className="px-6 py-4 text-center text-purple-600 font-semibold">★★★☆☆</td></tr>
                    <tr className="hover:bg-gray-50"><td className="px-6 py-4 font-medium text-gray-900">Cabo Negro</td><td className="px-6 py-4 text-center text-sky-600 font-semibold">20 km</td><td className="px-6 py-4 text-center text-blue-600 font-semibold">25 min</td><td className="px-6 py-4 text-center text-indigo-600 font-semibold">Panorámica</td><td className="px-6 py-4 text-center text-purple-600 font-semibold">★★★★☆</td></tr>
                    <tr className="bg-sky-50 hover:bg-sky-100"><td className="px-6 py-4 font-medium text-gray-900">Chefchaouen</td><td className="px-6 py-4 text-center text-sky-600 font-semibold">70 km</td><td className="px-6 py-4 text-center text-blue-600 font-semibold">1h20</td><td className="px-6 py-4 text-center text-indigo-600 font-semibold">Montaña</td><td className="px-6 py-4 text-center text-purple-600 font-semibold">★★★★★</td></tr>
                    <tr className="hover:bg-gray-50"><td className="px-6 py-4 font-medium text-gray-900">Tánger</td><td className="px-6 py-4 text-center text-sky-600 font-semibold">65 km</td><td className="px-6 py-4 text-center text-blue-600 font-semibold">1h00</td><td className="px-6 py-4 text-center text-indigo-600 font-semibold">Autopista</td><td className="px-6 py-4 text-center text-purple-600 font-semibold">★★★★★</td></tr>
                  </tbody>
                </table>
              </div>

              <div className="bg-gradient-to-r from-green-50 to-emerald-50 p-6 rounded-2xl mb-8"><h4 className="text-xl font-bold text-gray-900 mb-4 flex items-center"><Gift className="h-6 w-6 text-green-600 mr-2" />Servicios incluidos aeropuerto</h4><div className="grid md:grid-cols-2 gap-4"><ul className="space-y-2"><li className="flex items-center"><CheckCircle className="h-4 w-4 text-green-500 mr-2" /><span className="text-gray-700">Recepción personalizada</span></li><li className="flex items-center"><CheckCircle className="h-4 w-4 text-green-500 mr-2" /><span className="text-gray-700">Seguimiento automático de vuelos</span></li><li className="flex items-center"><CheckCircle className="h-4 w-4 text-green-500 mr-2" /><span className="text-gray-700">Espera gratuita 1 hora</span></li><li className="flex items-center"><CheckCircle className="h-4 w-4 text-green-500 mr-2" /><span className="text-gray-700">Formalidades exprés 5 min</span></li><li className="flex items-center"><CheckCircle className="h-4 w-4 text-green-500 mr-2" /><span className="text-gray-700">GPS configurado</span></li></ul><ul className="space-y-2"><li className="flex items-center"><CheckCircle className="h-4 w-4 text-green-500 mr-2" /><span className="text-gray-700">Guía región Norte</span></li><li className="flex items-center"><CheckCircle className="h-4 w-4 text-green-500 mr-2" /><span className="text-gray-700">Asistencia 24/7</span></li><li className="flex items-center"><CheckCircle className="h-4 w-4 text-green-500 mr-2" /><span className="text-gray-700">Combustible inicial incluido</span></li><li className="flex items-center"><CheckCircle className="h-4 w-4 text-green-500 mr-2" /><span className="text-gray-700">Devolución flexible (aeropuerto/ciudad)</span></li><li className="flex items-center"><CheckCircle className="h-4 w-4 text-green-500 mr-2" /><span className="text-gray-700">Soporte multilingüe</span></li></ul></div></div>
            </article>
          </div>

          <div className="lg:col-span-1">
            <div className="sticky top-8 space-y-8">
              <div className="bg-gradient-to-br from-sky-600 to-blue-700 text-white p-8 rounded-2xl shadow-xl"><h3 className="text-2xl font-bold mb-4">¡Servicio Exprés!</h3><p className="mb-6 text-sky-100">Recepción en terminal, recogida 5 min y salida inmediata.</p><Link href="/es/fleet" className="block w-full bg-white text-sky-600 font-bold py-3 px-6 rounded-xl text-center hover:bg-gray-50 transition-colors">Reservar Aeropuerto</Link></div>
              <div className="bg-white border border-gray-200 rounded-2xl p-6 shadow-sm"><h3 className="text-xl font-bold text-gray-900 mb-4">Información aeropuerto</h3><div className="space-y-3"><div className="flex items-center justify-between p-3 bg-sky-50 rounded-lg"><span className="text-gray-700">Código IATA</span><span className="text-sky-600 font-semibold">TTU</span></div><div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg"><span className="text-gray-700">Distancia al centro</span><span className="text-blue-600 font-semibold">5 km</span></div><div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg"><span className="text-gray-700">Tiempo de trayecto</span><span className="text-indigo-600 font-semibold">10 min</span></div><div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg"><span className="text-gray-700">Servicio</span><span className="text-purple-600 font-semibold">24/7</span></div></div></div>
              <div className="bg-white border border-gray-200 rounded-2xl p-6 shadow-sm"><h3 className="text-xl font-bold text-gray-900 mb-4">Destinos exprés</h3><div className="space-y-3"><div className="flex items-center justify-between p-3 bg-sky-50 rounded-lg"><span className="text-gray-700">Centro Tetuán</span><span className="text-sky-600 font-semibold">10 min</span></div><div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg"><span className="text-gray-700">Martil playa</span><span className="text-blue-600 font-semibold">20 min</span></div><div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg"><span className="text-gray-700">Chefchaouen</span><span className="text-indigo-600 font-semibold">1h20</span></div><div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg"><span className="text-gray-700">Tánger</span><span className="text-purple-600 font-semibold">1h00</span></div></div></div>
              <div className="bg-white border border-gray-200 rounded-2xl p-6 shadow-sm"><h3 className="text-xl font-bold text-gray-900 mb-4">Vehículos aeropuerto</h3><div className="space-y-3"><div className="flex items-center justify-between p-3 bg-sky-50 rounded-lg"><span className="text-gray-700">Económico</span><span className="text-sky-600 font-semibold">175 DH/d</span></div><div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg"><span className="text-gray-700">Familiar</span><span className="text-blue-600 font-semibold">220 DH/d</span></div><div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg"><span className="text-gray-700">SUV</span><span className="text-indigo-600 font-semibold">280 DH/d</span></div><div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg"><span className="text-gray-700">Premium</span><span className="text-purple-600 font-semibold">350 DH/d</span></div></div></div>
              <div className="bg-white border border-gray-200 rounded-2xl p-6 shadow-sm"><h3 className="text-xl font-bold text-gray-900 mb-4">Contacto aeropuerto</h3><div className="space-y-4"><div className="flex items-center"><Phone className="h-5 w-5 text-sky-600 mr-3" /><span className="text-gray-700">+212 631-630013</span></div><div className="flex items-center"><Mail className="h-5 w-5 text-sky-600 mr-3" /><span className="text-gray-700">aeropuerto@nassouhcar.com</span></div><div className="flex items-start"><Plane className="h-5 w-5 text-sky-600 mr-3 mt-1" /><span className="text-gray-700">Terminal de llegadas Sania Ramel</span></div></div><div className="mt-4 p-3 bg-sky-50 rounded-lg"><p className="text-sm text-sky-800 font-semibold">✈️ Servicio 24/7 todos los vuelos</p></div></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
